Class {
	#name : #MAResult,
	#superclass : #FFIEnumeration,
	#classVars : [
		'MA_ACCESS_DENIED',
		'MA_ADDRESS_FAMILY_NOT_SUPPORTED',
		'MA_ALREADY_CONNECTED',
		'MA_ALREADY_EXISTS',
		'MA_ALREADY_IN_USE',
		'MA_API_NOT_FOUND',
		'MA_AT_END',
		'MA_BACKEND_NOT_ENABLED',
		'MA_BAD_ADDRESS',
		'MA_BAD_MESSAGE',
		'MA_BAD_PIPE',
		'MA_BAD_PROTOCOL',
		'MA_BAD_SEEK',
		'MA_BUSY',
		'MA_CANCELLED',
		'MA_CONNECTION_REFUSED',
		'MA_CONNECTION_RESET',
		'MA_CRC_MISMATCH',
		'MA_DEADLOCK',
		'MA_DEVICE_ALREADY_INITIALIZED',
		'MA_DEVICE_NOT_INITIALIZED',
		'MA_DEVICE_NOT_STARTED',
		'MA_DEVICE_NOT_STOPPED',
		'MA_DEVICE_TYPE_NOT_SUPPORTED',
		'MA_DIRECTORY_NOT_EMPTY',
		'MA_DOES_NOT_EXIST',
		'MA_ERROR',
		'MA_FAILED_TO_INIT_BACKEND',
		'MA_FAILED_TO_OPEN_BACKEND_DEVICE',
		'MA_FAILED_TO_START_BACKEND_DEVICE',
		'MA_FAILED_TO_STOP_BACKEND_DEVICE',
		'MA_FORMAT_NOT_SUPPORTED',
		'MA_INTERRUPT',
		'MA_INVALID_ARGS',
		'MA_INVALID_DATA',
		'MA_INVALID_DEVICE_CONFIG',
		'MA_INVALID_FILE',
		'MA_INVALID_OPERATION',
		'MA_IN_PROGRESS',
		'MA_IO_ERROR',
		'MA_IS_DIRECTORY',
		'MA_LOOP',
		'MA_MEMORY_ALREADY_MAPPED',
		'MA_NAME_TOO_LONG',
		'MA_NOT_CONNECTED',
		'MA_NOT_DIRECTORY',
		'MA_NOT_IMPLEMENTED',
		'MA_NOT_SOCKET',
		'MA_NOT_UNIQUE',
		'MA_NO_ADDRESS',
		'MA_NO_BACKEND',
		'MA_NO_DATA_AVAILABLE',
		'MA_NO_DEVICE',
		'MA_NO_HOST',
		'MA_NO_MESSAGE',
		'MA_NO_NETWORK',
		'MA_NO_SPACE',
		'MA_OUT_OF_MEMORY',
		'MA_OUT_OF_RANGE',
		'MA_PATH_TOO_LONG',
		'MA_PROTOCOL_FAMILY_NOT_SUPPORTED',
		'MA_PROTOCOL_NOT_SUPPORTED',
		'MA_PROTOCOL_UNAVAILABLE',
		'MA_SHARE_MODE_NOT_SUPPORTED',
		'MA_SOCKET_NOT_SUPPORTED',
		'MA_SUCCESS',
		'MA_TIMEOUT',
		'MA_TOO_BIG',
		'MA_TOO_MANY_LINKS',
		'MA_TOO_MANY_OPEN_FILES',
		'MA_UNAVAILABLE'
	],
	#category : #LetUsRead
}

{ #category : #'accessing enum' }
MAResult class >> MA_ACCESS_DENIED [
	"This method was automatically generated"
	^ MA_ACCESS_DENIED
]

{ #category : #'accessing enum' }
MAResult class >> MA_ADDRESS_FAMILY_NOT_SUPPORTED [
	"This method was automatically generated"
	^ MA_ADDRESS_FAMILY_NOT_SUPPORTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_ALREADY_CONNECTED [
	"This method was automatically generated"
	^ MA_ALREADY_CONNECTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_ALREADY_EXISTS [
	"This method was automatically generated"
	^ MA_ALREADY_EXISTS
]

{ #category : #'accessing enum' }
MAResult class >> MA_ALREADY_IN_USE [
	"This method was automatically generated"
	^ MA_ALREADY_IN_USE
]

{ #category : #'accessing enum' }
MAResult class >> MA_API_NOT_FOUND [
	"This method was automatically generated"
	^ MA_API_NOT_FOUND
]

{ #category : #'accessing enum' }
MAResult class >> MA_AT_END [
	"This method was automatically generated"
	^ MA_AT_END
]

{ #category : #'accessing enum' }
MAResult class >> MA_BACKEND_NOT_ENABLED [
	"This method was automatically generated"
	^ MA_BACKEND_NOT_ENABLED
]

{ #category : #'accessing enum' }
MAResult class >> MA_BAD_ADDRESS [
	"This method was automatically generated"
	^ MA_BAD_ADDRESS
]

{ #category : #'accessing enum' }
MAResult class >> MA_BAD_MESSAGE [
	"This method was automatically generated"
	^ MA_BAD_MESSAGE
]

{ #category : #'accessing enum' }
MAResult class >> MA_BAD_PIPE [
	"This method was automatically generated"
	^ MA_BAD_PIPE
]

{ #category : #'accessing enum' }
MAResult class >> MA_BAD_PROTOCOL [
	"This method was automatically generated"
	^ MA_BAD_PROTOCOL
]

{ #category : #'accessing enum' }
MAResult class >> MA_BAD_SEEK [
	"This method was automatically generated"
	^ MA_BAD_SEEK
]

{ #category : #'accessing enum' }
MAResult class >> MA_BUSY [
	"This method was automatically generated"
	^ MA_BUSY
]

{ #category : #'accessing enum' }
MAResult class >> MA_CANCELLED [
	"This method was automatically generated"
	^ MA_CANCELLED
]

{ #category : #'accessing enum' }
MAResult class >> MA_CONNECTION_REFUSED [
	"This method was automatically generated"
	^ MA_CONNECTION_REFUSED
]

{ #category : #'accessing enum' }
MAResult class >> MA_CONNECTION_RESET [
	"This method was automatically generated"
	^ MA_CONNECTION_RESET
]

{ #category : #'accessing enum' }
MAResult class >> MA_CRC_MISMATCH [
	"This method was automatically generated"
	^ MA_CRC_MISMATCH
]

{ #category : #'accessing enum' }
MAResult class >> MA_DEADLOCK [
	"This method was automatically generated"
	^ MA_DEADLOCK
]

{ #category : #'accessing enum' }
MAResult class >> MA_DEVICE_ALREADY_INITIALIZED [
	"This method was automatically generated"
	^ MA_DEVICE_ALREADY_INITIALIZED
]

{ #category : #'accessing enum' }
MAResult class >> MA_DEVICE_NOT_INITIALIZED [
	"This method was automatically generated"
	^ MA_DEVICE_NOT_INITIALIZED
]

{ #category : #'accessing enum' }
MAResult class >> MA_DEVICE_NOT_STARTED [
	"This method was automatically generated"
	^ MA_DEVICE_NOT_STARTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_DEVICE_NOT_STOPPED [
	"This method was automatically generated"
	^ MA_DEVICE_NOT_STOPPED
]

{ #category : #'accessing enum' }
MAResult class >> MA_DEVICE_TYPE_NOT_SUPPORTED [
	"This method was automatically generated"
	^ MA_DEVICE_TYPE_NOT_SUPPORTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_DIRECTORY_NOT_EMPTY [
	"This method was automatically generated"
	^ MA_DIRECTORY_NOT_EMPTY
]

{ #category : #'accessing enum' }
MAResult class >> MA_DOES_NOT_EXIST [
	"This method was automatically generated"
	^ MA_DOES_NOT_EXIST
]

{ #category : #'accessing enum' }
MAResult class >> MA_ERROR [
	"This method was automatically generated"
	^ MA_ERROR
]

{ #category : #'accessing enum' }
MAResult class >> MA_FAILED_TO_INIT_BACKEND [
	"This method was automatically generated"
	^ MA_FAILED_TO_INIT_BACKEND
]

{ #category : #'accessing enum' }
MAResult class >> MA_FAILED_TO_OPEN_BACKEND_DEVICE [
	"This method was automatically generated"
	^ MA_FAILED_TO_OPEN_BACKEND_DEVICE
]

{ #category : #'accessing enum' }
MAResult class >> MA_FAILED_TO_START_BACKEND_DEVICE [
	"This method was automatically generated"
	^ MA_FAILED_TO_START_BACKEND_DEVICE
]

{ #category : #'accessing enum' }
MAResult class >> MA_FAILED_TO_STOP_BACKEND_DEVICE [
	"This method was automatically generated"
	^ MA_FAILED_TO_STOP_BACKEND_DEVICE
]

{ #category : #'accessing enum' }
MAResult class >> MA_FORMAT_NOT_SUPPORTED [
	"This method was automatically generated"
	^ MA_FORMAT_NOT_SUPPORTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_INTERRUPT [
	"This method was automatically generated"
	^ MA_INTERRUPT
]

{ #category : #'accessing enum' }
MAResult class >> MA_INVALID_ARGS [
	"This method was automatically generated"
	^ MA_INVALID_ARGS
]

{ #category : #'accessing enum' }
MAResult class >> MA_INVALID_DATA [
	"This method was automatically generated"
	^ MA_INVALID_DATA
]

{ #category : #'accessing enum' }
MAResult class >> MA_INVALID_DEVICE_CONFIG [
	"This method was automatically generated"
	^ MA_INVALID_DEVICE_CONFIG
]

{ #category : #'accessing enum' }
MAResult class >> MA_INVALID_FILE [
	"This method was automatically generated"
	^ MA_INVALID_FILE
]

{ #category : #'accessing enum' }
MAResult class >> MA_INVALID_OPERATION [
	"This method was automatically generated"
	^ MA_INVALID_OPERATION
]

{ #category : #'accessing enum' }
MAResult class >> MA_IN_PROGRESS [
	"This method was automatically generated"
	^ MA_IN_PROGRESS
]

{ #category : #'accessing enum' }
MAResult class >> MA_IO_ERROR [
	"This method was automatically generated"
	^ MA_IO_ERROR
]

{ #category : #'accessing enum' }
MAResult class >> MA_IS_DIRECTORY [
	"This method was automatically generated"
	^ MA_IS_DIRECTORY
]

{ #category : #'accessing enum' }
MAResult class >> MA_LOOP [
	"This method was automatically generated"
	^ MA_LOOP
]

{ #category : #'accessing enum' }
MAResult class >> MA_MEMORY_ALREADY_MAPPED [
	"This method was automatically generated"
	^ MA_MEMORY_ALREADY_MAPPED
]

{ #category : #'accessing enum' }
MAResult class >> MA_NAME_TOO_LONG [
	"This method was automatically generated"
	^ MA_NAME_TOO_LONG
]

{ #category : #'accessing enum' }
MAResult class >> MA_NOT_CONNECTED [
	"This method was automatically generated"
	^ MA_NOT_CONNECTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_NOT_DIRECTORY [
	"This method was automatically generated"
	^ MA_NOT_DIRECTORY
]

{ #category : #'accessing enum' }
MAResult class >> MA_NOT_IMPLEMENTED [
	"This method was automatically generated"
	^ MA_NOT_IMPLEMENTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_NOT_SOCKET [
	"This method was automatically generated"
	^ MA_NOT_SOCKET
]

{ #category : #'accessing enum' }
MAResult class >> MA_NOT_UNIQUE [
	"This method was automatically generated"
	^ MA_NOT_UNIQUE
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_ADDRESS [
	"This method was automatically generated"
	^ MA_NO_ADDRESS
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_BACKEND [
	"This method was automatically generated"
	^ MA_NO_BACKEND
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_DATA_AVAILABLE [
	"This method was automatically generated"
	^ MA_NO_DATA_AVAILABLE
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_DEVICE [
	"This method was automatically generated"
	^ MA_NO_DEVICE
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_HOST [
	"This method was automatically generated"
	^ MA_NO_HOST
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_MESSAGE [
	"This method was automatically generated"
	^ MA_NO_MESSAGE
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_NETWORK [
	"This method was automatically generated"
	^ MA_NO_NETWORK
]

{ #category : #'accessing enum' }
MAResult class >> MA_NO_SPACE [
	"This method was automatically generated"
	^ MA_NO_SPACE
]

{ #category : #'accessing enum' }
MAResult class >> MA_OUT_OF_MEMORY [
	"This method was automatically generated"
	^ MA_OUT_OF_MEMORY
]

{ #category : #'accessing enum' }
MAResult class >> MA_OUT_OF_RANGE [
	"This method was automatically generated"
	^ MA_OUT_OF_RANGE
]

{ #category : #'accessing enum' }
MAResult class >> MA_PATH_TOO_LONG [
	"This method was automatically generated"
	^ MA_PATH_TOO_LONG
]

{ #category : #'accessing enum' }
MAResult class >> MA_PROTOCOL_FAMILY_NOT_SUPPORTED [
	"This method was automatically generated"
	^ MA_PROTOCOL_FAMILY_NOT_SUPPORTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_PROTOCOL_NOT_SUPPORTED [
	"This method was automatically generated"
	^ MA_PROTOCOL_NOT_SUPPORTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_PROTOCOL_UNAVAILABLE [
	"This method was automatically generated"
	^ MA_PROTOCOL_UNAVAILABLE
]

{ #category : #'accessing enum' }
MAResult class >> MA_SHARE_MODE_NOT_SUPPORTED [
	"This method was automatically generated"
	^ MA_SHARE_MODE_NOT_SUPPORTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_SOCKET_NOT_SUPPORTED [
	"This method was automatically generated"
	^ MA_SOCKET_NOT_SUPPORTED
]

{ #category : #'accessing enum' }
MAResult class >> MA_SUCCESS [
	"This method was automatically generated"
	^ MA_SUCCESS
]

{ #category : #'accessing enum' }
MAResult class >> MA_TIMEOUT [
	"This method was automatically generated"
	^ MA_TIMEOUT
]

{ #category : #'accessing enum' }
MAResult class >> MA_TOO_BIG [
	"This method was automatically generated"
	^ MA_TOO_BIG
]

{ #category : #'accessing enum' }
MAResult class >> MA_TOO_MANY_LINKS [
	"This method was automatically generated"
	^ MA_TOO_MANY_LINKS
]

{ #category : #'accessing enum' }
MAResult class >> MA_TOO_MANY_OPEN_FILES [
	"This method was automatically generated"
	^ MA_TOO_MANY_OPEN_FILES
]

{ #category : #'accessing enum' }
MAResult class >> MA_UNAVAILABLE [
	"This method was automatically generated"
	^ MA_UNAVAILABLE
]

{ #category : #'enum declaration' }
MAResult class >> enumDecl [
	"
	self initialize.
	self rebuildEnumAccessors
	"
	^ #(
    MA_SUCCESS                         0
    MA_ERROR                          -1  "A generic error."
    MA_INVALID_ARGS                   -2
    MA_INVALID_OPERATION              -3
    MA_OUT_OF_MEMORY                  -4
    MA_OUT_OF_RANGE                   -5
    MA_ACCESS_DENIED                  -6
    MA_DOES_NOT_EXIST                 -7
    MA_ALREADY_EXISTS                 -8
    MA_TOO_MANY_OPEN_FILES            -9
    MA_INVALID_FILE                   -10
    MA_TOO_BIG                        -11
    MA_PATH_TOO_LONG                  -12
    MA_NAME_TOO_LONG                  -13
    MA_NOT_DIRECTORY                  -14
    MA_IS_DIRECTORY                   -15
    MA_DIRECTORY_NOT_EMPTY            -16
    MA_AT_END                         -17
    MA_NO_SPACE                       -18
    MA_BUSY                           -19
    MA_IO_ERROR                       -20
    MA_INTERRUPT                      -21
    MA_UNAVAILABLE                    -22
    MA_ALREADY_IN_USE                 -23
    MA_BAD_ADDRESS                    -24
    MA_BAD_SEEK                       -25
    MA_BAD_PIPE                       -26
    MA_DEADLOCK                       -27
    MA_TOO_MANY_LINKS                 -28
    MA_NOT_IMPLEMENTED                -29
    MA_NO_MESSAGE                     -30
    MA_BAD_MESSAGE                    -31
    MA_NO_DATA_AVAILABLE              -32
    MA_INVALID_DATA                   -33
    MA_TIMEOUT                        -34
    MA_NO_NETWORK                     -35
    MA_NOT_UNIQUE                     -36
    MA_NOT_SOCKET                     -37
    MA_NO_ADDRESS                     -38
    MA_BAD_PROTOCOL                   -39
    MA_PROTOCOL_UNAVAILABLE           -40
    MA_PROTOCOL_NOT_SUPPORTED         -41
    MA_PROTOCOL_FAMILY_NOT_SUPPORTED  -42
    MA_ADDRESS_FAMILY_NOT_SUPPORTED   -43
    MA_SOCKET_NOT_SUPPORTED           -44
    MA_CONNECTION_RESET               -45
    MA_ALREADY_CONNECTED              -46
    MA_NOT_CONNECTED                  -47
    MA_CONNECTION_REFUSED             -48
    MA_NO_HOST                        -49
    MA_IN_PROGRESS                    -50
    MA_CANCELLED                      -51
    MA_MEMORY_ALREADY_MAPPED          -52

    "General non-standard errors."
    MA_CRC_MISMATCH                   -100

    "General miniaudio-specific errors."
    MA_FORMAT_NOT_SUPPORTED           -200
    MA_DEVICE_TYPE_NOT_SUPPORTED      -201
    MA_SHARE_MODE_NOT_SUPPORTED       -202
    MA_NO_BACKEND                     -203
    MA_NO_DEVICE                      -204
    MA_API_NOT_FOUND                  -205
    MA_INVALID_DEVICE_CONFIG          -206
    MA_LOOP                           -207
    MA_BACKEND_NOT_ENABLED            -208

    "State errors."
    MA_DEVICE_NOT_INITIALIZED         -300
    MA_DEVICE_ALREADY_INITIALIZED     -301
    MA_DEVICE_NOT_STARTED             -302
    MA_DEVICE_NOT_STOPPED             -303

    "Operation errors."
    MA_FAILED_TO_INIT_BACKEND         -400
    MA_FAILED_TO_OPEN_BACKEND_DEVICE  -401
    MA_FAILED_TO_START_BACKEND_DEVICE -402
    MA_FAILED_TO_STOP_BACKEND_DEVICE  -403
	)
]

{ #category : #initalization }
MAResult class >> initialize [
	super initialize
]
